#!/usr/bin/bash

# PID=$(pgrep -f 'gnome-session' | head -n1)
# export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ | cut -d= -f2- ) 

gsettings set org.gnome.desktop.background picture-uri-dark "file:///$(find ~/Pictures/Walls/ -type f| shuf -n 1)"

