#!/bin/bash
set -e


pdftotext "$1" - | grep -oP "\b\d{4}.\d{5}v\d{1}"  | head -n 1 
pdftotext "$1" - | grep -oP "\b\d{4}.\d{4}v\d+" | head -n 1 
pdftotext "$1" - | grep -oP "\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![\"&\'<>])\S)+)\b" | head -n 1 

