#!/bin/bash
set -e

for pdf in *.pdf; do 
	pdftotext "$pdf" - | grep -oP "\b\d{4}.\d{5}v\d{1}" | head -n 1 
	pdftotext "$pdf" - | grep -oP "\b\d{4}.\d{4}v\d+" | head -n 1 
	pdftotext "$pdf" - | grep -oP "\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![\"&\'<>])\S)+)\b" | head -n 1 
done

